### ISSUE TITLE
気になるとこ

### ISSUE THREAD

**Issue by equal-l2** [h-takeyeah/ams-init-scripts#1]
- `unix_socket`を無効にしているのはなぜでしょうか。
https://github.com/h-takeyeah/ams-init-scripts/blob/36ad77284d5bec52e216981b7045ce6f8cb72e0d/01installer_beta.sh#L73-L74

- `NORMALUSER`に全権限を与えるのはちょっと怖いです。backendのソースを見る限りinsert,select,deleteしかやってないので、可能ならそれらに権限を絞って、テーブル作成等はrootでやった方がいいです。
https://github.com/h-takeyeah/ams-init-scripts/blob/36ad77284d5bec52e216981b7045ce6f8cb72e0d/01installer_beta.sh#L78-L83

**Comment by equal-l2** [comment]
あと、MariaDBを入れてから、他の作業を色々やって、またMariaDBに戻るという順番になっているので、MariaDB関連は一箇所にまとめておいた方がいいです。
(しばらく経ってから「さっきのパスワード」と言われると関連性がやや弱いので)

**Comment by equal-l2** [comment]
Ansibleの方では直ってるとかだったらOKですが

**Comment by h-takeyeah** [comment]
- `unix_socket`を無効にしているのはなぜか
`unix_socket`がオンだと`NORMALUSER`からSQLにクエリを飛ばしたいときに**unixのユーザーという意味での**`NORMALUSER`として実行されていないとうまく動きません．実際にラズパイでクエリを飛ばすのはpiユーザーですからそのような制約はない方が都合がよいです．なのでオフにしています．あとはコンソールから実行するときの話になりますが，例えば新しくDBを作りたいときなど(MariaDBの)rootユーザーの権限が必要な場合，`sudo mysql -uroot`といちいち`sudo`を付けなければいけないのが面倒だし物騒だからという理由もあります．

- `NORMALUSER`に全権限を与えないように
そうします

- 順序
修正します

**Comment by equal-l2** [comment]
> NORMALUSERからSQLにクエリを飛ばしたいときにunixのユーザーという意味でのNORMALUSERとして実行されていないとうまく動きません

手元で作った環境ではこれは再現しませんでした。
普通に`user`というMySQLアカウントにUnixアカウント`pi`の状態でログインできました。

> 新しくDBを作りたいときなど(MariaDBの)rootユーザーの権限が必要な場合，sudo mysql -urootといちいちsudoを付けなければいけないのが面倒だし物騒

DBを作成したりテーブルを作成する行為は実際「unix_socketでちゃんとしたユーザか確認してからやらせる」必要があるくらいには危険な行為です。
だからこそ「面倒だし物騒」なのです。

**Comment by h-takeyeah** [comment]
分かりました．unix_socket～の記述は削除しておこうと思います．(unix_socket有効な状態で運用する)

**Comment by equal-l2** [comment]
rootはunix_socketだけでパスワードを指定しないでおくと`sudo`だけで使えて便利です

**Comment by h-takeyeah** [comment]
unix_socketメモ https://hp.ofuton.org/61/
